services:
  - type: web
    name: travel-recommender
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      chmod +x start.sh  # Ensure script is executable
    startCommand: ./start.sh
    plan: free
