services:
  - type: web
    name: travel-recommender
    runtime: python
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
      python offline.py --batch-size 1  # Minimal memory usage
    startCommand: |
      gunicorn --workers=1 --threads=1 --timeout=300 --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: PORT
        value: 10000
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"  # Disables memory-intensive optimizations
    plan: free  # Upgrade to starter if still failing
