services:
  - type: web
    name: travel-recommender
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
      python offline.py --resume --batch-size 1
    startCommand: |
      gunicorn --workers=1 --threads=1 --timeout=300 \
               --worker-class=gthread \
               --bind 0.0.0.0:$PORT server:app
    envVars:
      - key: PORT
        value: 10000
      - key: TF_ENABLE_ONEDNN_OPTS
        value: "0"
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: "true"
    plan: free
